AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: FastAPI on AWS Lambda with Mangum

Resources:
  FastAPIFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_handler.handler
      Runtime: python3.10
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Events:
        FastAPIProxy:
          Type: Api
          Properties:
            Path: /
            Method: ANY
